import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { Josefin_Sans } from 'next/font/google';
import Header from "./components/header";


const josefinSans = Josefin_Sans({
  subsets: ['latin'], // Specify subsets
  variable: "--font-josefin-sans",
  weight: ['400', '500', '600', '700'], // Choose weights you need
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.variable} antialiased`}
      >
        <Header />
        <Navbar />
        
        {children}
        <Footer />
      </body>
    </html>
  );
}
